# Generated by Django 2.2 on 2020-05-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
