# Generated by Django 2.2 on 2020-05-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0002_auto_20200507_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='rating',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
